# Generated by Django 5.0.3 on 2024-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meuApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
